services:
  postgres:
    image: postgres:17
    container_name: delivery-postgres
    restart: always

    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - delivery-postgres-data:/var/lib/postgresql/data

volumes:
  delivery-postgres-data: