services:
  postgres:
    image: postgres:17
    container_name: delivery-postgres
    restart: always

    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - delivery-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.4
    container_name: delivery-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - delivery-redis-data:/data

volumes:
  delivery-postgres-data:
  delivery-redis-data:
