spring.application.name=delivery

# PostgreSQL
# PostgreSQL 기본 포트 5432 사용
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT 키 생성 : openssl rand -base64 32
jwt.access-secret=${JWT_ACCESS_SECRET}
jwt.refresh-secret=${JWT_REFRESH_SECRET}

# AesBytesEncryptor 키 생성 / openssl rand -base64 32 / openssl rand -hex 16
encrypt.key=${ENCRYPT_KEY}
encrypt.salt=${ENCRYPT_SALT}

# Gemini
gemini.api-key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-3.5-flash}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
