spring.application.name=delivery

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery
spring.datasource.username=postgres
spring.datasource.password=postgres1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT TODO : 임시 Key 추후 교체 필요 / openssl rand -base64 32
jwt.secret=zn5868t3GCgYcPLNJ7aporHLXPTedwWqXLIth67Nwb8=
jwt.refresh-secret=zn5868t3GCgYcPLNJ7aporHLXPTedwWqXLIth67Nwb8=

# AesBytesEncryptor TODO : 임시 Key 추후 교체 필요 / openssl rand -base64 32 / openssl rand -hex 16
encrypt.key=8qzv8E0VZEtnmloiNYDAmj/KJz2E7GeT5Hg02C3bi6o=
encrypt.salt=e81814d3cd292fcfaf6f47822eacb9e8

# Gemini
gemini.api-key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-3.5-flash}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
